# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm07.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm07.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63omm07.proto\"\x1b\n\nInfRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\x1a\n\x08InfReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1d\n\x0bPunkedReply\x12\x0e\n\x06punked\x18\x01 \x01(\t2T\n\x06\x43omm07\x12\"\n\x06Talker\x12\x0b.InfRequest\x1a\t.InfReply\"\x00\x12&\n\tget_punkt\x12\t.InfReply\x1a\x0c.PunkedReply\"\x00\x62\x06proto3'
)




_INFREQUEST = _descriptor.Descriptor(
  name='InfRequest',
  full_name='InfRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='InfRequest.audio', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=43,
)


_INFREPLY = _descriptor.Descriptor(
  name='InfReply',
  full_name='InfReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='InfReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=71,
)


_PUNKEDREPLY = _descriptor.Descriptor(
  name='PunkedReply',
  full_name='PunkedReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='punked', full_name='PunkedReply.punked', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['InfRequest'] = _INFREQUEST
DESCRIPTOR.message_types_by_name['InfReply'] = _INFREPLY
DESCRIPTOR.message_types_by_name['PunkedReply'] = _PUNKEDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InfRequest = _reflection.GeneratedProtocolMessageType('InfRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFREQUEST,
  '__module__' : 'comm07_pb2'
  # @@protoc_insertion_point(class_scope:InfRequest)
  })
_sym_db.RegisterMessage(InfRequest)

InfReply = _reflection.GeneratedProtocolMessageType('InfReply', (_message.Message,), {
  'DESCRIPTOR' : _INFREPLY,
  '__module__' : 'comm07_pb2'
  # @@protoc_insertion_point(class_scope:InfReply)
  })
_sym_db.RegisterMessage(InfReply)

PunkedReply = _reflection.GeneratedProtocolMessageType('PunkedReply', (_message.Message,), {
  'DESCRIPTOR' : _PUNKEDREPLY,
  '__module__' : 'comm07_pb2'
  # @@protoc_insertion_point(class_scope:PunkedReply)
  })
_sym_db.RegisterMessage(PunkedReply)



_COMM07 = _descriptor.ServiceDescriptor(
  name='Comm07',
  full_name='Comm07',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=188,
  methods=[
  _descriptor.MethodDescriptor(
    name='Talker',
    full_name='Comm07.Talker',
    index=0,
    containing_service=None,
    input_type=_INFREQUEST,
    output_type=_INFREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_punkt',
    full_name='Comm07.get_punkt',
    index=1,
    containing_service=None,
    input_type=_INFREPLY,
    output_type=_PUNKEDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMM07)

DESCRIPTOR.services_by_name['Comm07'] = _COMM07

# @@protoc_insertion_point(module_scope)
